// <auto-generated />
using System;
using DelikatessenDrehbuch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DelikatessenDrehbuch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420212742_AddIngredientMeasureQuantityLinkToAiVariantRows")]
    partial class AddIngredientMeasureQuantityLinkToAiVariantRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.JoinIngredientPreparationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("PreperationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("PreperationId");

                    b.ToTable("JoinIngredientPreperationStep", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Word_DE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word_ESP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word_PRT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.MealPlanListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeCount")
                        .HasColumnType("int");

                    b.Property<string>("SellerHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerUsdtWalletAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerWalletAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("SellerHash");

                    b.HasIndex("IsActive", "CreatedAt");

                    b.ToTable("MealPlanListings");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.MealPlanPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyerHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuyerWalletAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedMealPlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("CreatorAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceTxHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerWalletAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerHash");

                    b.HasIndex("ListingId");

                    b.HasIndex("ReferenceTxHash")
                        .IsUnique()
                        .HasFilter("[ReferenceTxHash] IS NOT NULL");

                    b.HasIndex("SellerHash");

                    b.ToTable("WorldMealplanPurcase", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("AppliedChangeCount")
                        .HasColumnType("int");

                    b.Property<int>("BaseRecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IngredientsText")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSharedCanonical")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("LatestUserNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ParentVariantId")
                        .HasColumnType("int");

                    b.Property<string>("PreparationText")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedHighlightsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedIngredientsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedStepsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RenderedTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SelectedIngredientKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("StepPlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariantType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ParentVariantId");

                    b.HasIndex("BaseRecipeId", "CreatedByUserHash", "VariantType", "Language", "AiProvider", "SelectedIngredientKey");

                    b.HasIndex("BaseRecipeId", "VariantType", "Language", "AiProvider", "SelectedIngredientKey", "IsSharedCanonical");

                    b.ToTable("RecipeAiVariants", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariantIngredientRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientMeasureQuantityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("bit");

                    b.Property<int?>("MeasureId")
                        .HasColumnType("int");

                    b.Property<string>("QuantityText")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("RecipeAiVariantId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("IngredientMeasureQuantityId");

                    b.HasIndex("MeasureId");

                    b.HasIndex("RecipeAiVariantId", "SortOrder");

                    b.ToTable("RecipeAiVariantIngredientRows", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariantSelectedIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeAiVariantId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeAiVariantId", "IngredientId")
                        .IsUnique();

                    b.HasIndex("RecipeAiVariantId", "SortOrder");

                    b.ToTable("RecipeAiVariantSelectedIngredients", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeBaseKeyword", b =>
                {
                    b.Property<int>("RecipeBaseDataId")
                        .HasColumnType("int");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int");

                    b.HasKey("RecipeBaseDataId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("RecipeBaseKeywords");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WildCoinTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserHash", "CreatedAt");

                    b.ToTable("WildCoinTransactions");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldAdPreferenceInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InterestKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InterestType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastSignalAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SignalCount")
                        .HasColumnType("int");

                    b.Property<string>("UserHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserHash", "InterestType", "Score");

                    b.ToTable("WorldAdPreferenceInterests");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldAdPreferenceProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowCategoryTargeting")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowCreatorTargeting")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowKeywordTargeting")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPersonalizedAds")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FollowedCreatorCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastProfileRefreshUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LikedRecipeCount")
                        .HasColumnType("int");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QualifiedWatchCount")
                        .HasColumnType("int");

                    b.Property<string>("SegmentLabelsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopCategoriesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopCreatorsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopKeywordsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserHash")
                        .IsUnique();

                    b.ToTable("WorldAdPreferenceProfiles");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldAppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsVerified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Lastlogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RememberLogin")
                        .HasColumnType("bit");

                    b.Property<string>("UserHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WildCoinBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserHash")
                        .IsUnique()
                        .HasFilter("[UserHash] IS NOT NULL");

                    b.ToTable("WorldAppUser");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldClipWatchSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsQualifiedView")
                        .HasColumnType("bit");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionEndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViewerUserHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("WatchedSeconds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("WorldUserPostingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorldUserPostingId");

                    b.HasIndex("ViewerUserHash", "CreatedAtUtc");

                    b.HasIndex("CreatorUserHash", "IsQualifiedView", "CreatedAtUtc");

                    b.ToTable("WorldClipWatchSessions");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldSharedMealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealPlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonCount")
                        .HasColumnType("int");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoppingListJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorldSharedMealPlan");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldSharedShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckedJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShareToken");

                    b.ToTable("WorldSharedShoppingList");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserAbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("WorldUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("WorldUserId");

                    b.ToTable("WorldUserAbo");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("WorldAppUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("WorldAppUserId");

                    b.ToTable("WorldUserBookmark");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("WorldAppUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("WorldAppUserId");

                    b.ToTable("WorldUserLike");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserMealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserHash");

                    b.HasIndex("UserHash", "Title");

                    b.ToTable("WorldUserMealPlan");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("bit");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RecipeId");

                    b.ToTable("WorldUserPosting");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Category_Key");

                    b.Property<string>("Name_DE")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_DK")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_EN")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_ESP")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_ID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_MS")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_NL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_NO")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_PRT")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name_SE")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryKey")
                        .IsUnique();

                    b.ToTable("food_categories", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AverageWeight")
                        .HasColumnType("real");

                    b.Property<float?>("Calories")
                        .HasColumnType("real");

                    b.Property<bool?>("GrammOnly")
                        .HasColumnType("bit");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.IngredientHandlerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("MeasureId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasureId");

                    b.HasIndex("QuantityId");

                    b.ToTable("IngredientHandlers");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.IngredientMeasureQuantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientsAndNutrientsId")
                        .HasColumnType("int");

                    b.Property<int>("MeasureId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientsAndNutrientsId");

                    b.HasIndex("MeasureId");

                    b.HasIndex("QuantityId");

                    b.ToTable("IngredientMeasureQuantity");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.IngredientsAndNutrients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories_a_100g")
                        .HasColumnType("int");

                    b.Property<decimal>("Carbohydrates_a_100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fat_a_100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fiber_a_100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FoodCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Genus_DE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_DK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_ESP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_MS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_NL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_PRT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus_SE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_DE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_DK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_ESP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_MS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_NL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_PRT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_SE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Protein_a_100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salt_a_100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Saturated_fat_a_100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sugar_a_100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Weight_per_piece")
                        .HasColumnType("int");

                    b.Property<bool>("is_blendable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_boilable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_cuttable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_fat")
                        .HasColumnType("bit");

                    b.Property<bool>("is_flambeable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_fryable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_grateable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_grillable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_hard")
                        .HasColumnType("bit");

                    b.Property<bool>("is_liquid")
                        .HasColumnType("bit");

                    b.Property<bool>("is_peelable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_poachable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_powder")
                        .HasColumnType("bit");

                    b.Property<bool>("is_roastable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_searable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_smokable")
                        .HasColumnType("bit");

                    b.Property<bool>("is_soft")
                        .HasColumnType("bit");

                    b.Property<bool>("is_steamable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FoodCategoryId");

                    b.HasIndex("GroupId");

                    b.ToTable("IngredientsAndNutrients");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UserMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MyMealModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preperation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MyMealModelId");

                    b.ToTable("MealPlan");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.MealPlanHandler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("RecipesId");

                    b.ToTable("MealPlanHandler");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.MealplanFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealplanFilter");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Metrics_DE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_DE");

                    b.Property<string>("Metrics_DK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_DK");

                    b.Property<string>("Metrics_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_EN");

                    b.Property<string>("Metrics_ESP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_ESP");

                    b.Property<string>("Metrics_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_ID");

                    b.Property<string>("Metrics_MS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_MS");

                    b.Property<string>("Metrics_NL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_NL");

                    b.Property<string>("Metrics_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_NO");

                    b.Property<string>("Metrics_PRT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_PRT");

                    b.Property<string>("Metrics_SE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metriks_SE");

                    b.HasKey("Id");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.MyMealModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MyMealModel");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.NutrienHandler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("MetricsId")
                        .HasColumnType("int");

                    b.Property<int>("NutrientsId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MetricsId");

                    b.HasIndex("NutrientsId");

                    b.HasIndex("QuantityId");

                    b.ToTable("NutrienHandler");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Nutrients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nutrient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Quantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Quantitys")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Quantities");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Queries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Querys", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.QueryHandler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QueryId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.HasIndex("RecipeId");

                    b.ToTable("QueryHandler");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Recession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assessment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipesId");

                    b.ToTable("Recessions");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeBaseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("PersonCount")
                        .HasColumnType("int");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int")
                        .HasColumnName("PreperationTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("RecipeBaseData");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeBaseDataImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<bool>("WorldAppImage")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeBaseDataImage");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeJoinIngredientMeasureQuantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeJoinIngredientMeasureQuantity");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeJoinPreparationSteps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("RecipePreperationStepId")
                        .HasColumnType("int");

                    b.Property<int>("StepIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RecipePreperationStepId");

                    b.ToTable("RecipeJoinPreperationSteps", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeJoinSmartStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SmartRecipeStepId")
                        .HasColumnType("int");

                    b.Property<int>("StepIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SmartRecipeStepId");

                    b.HasIndex("RecipeId", "StepIndex");

                    b.ToTable("RecipeJoinSmartSteps", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipePreparationSteps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Equipment")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("Step_DE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Step_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Step_ESP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Step_PRT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecipePreperationSteps", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Recipes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int?>("RecipePersonCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipesHandler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IngredientHandlerId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientHandlerId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipesHandlers");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.SavedMealPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealPlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonCount")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserSettingJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SavedMealPlan");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.SmartRecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Equipment")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MasterStepKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("VariablesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MasterStepKey", "Phase", "Equipment");

                    b.ToTable("SmartRecipeSteps", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SupportMessage");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.UserPreferencesQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPreferencesQuerys", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.UserPreferencesRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipesId");

                    b.ToTable("UserPreferencesRecipes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.JoinIngredientPreparationStep", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.IngredientsAndNutrients", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.RecipePreparationSteps", "Preparation")
                        .WithMany()
                        .HasForeignKey("PreperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Preparation");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.MealPlanListing", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserMealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.MealPlanPurchase", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.MealPlanListing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariant", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "BaseRecipe")
                        .WithMany()
                        .HasForeignKey("BaseRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariant", "ParentVariant")
                        .WithMany()
                        .HasForeignKey("ParentVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BaseRecipe");

                    b.Navigation("ParentVariant");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariantIngredientRow", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.IngredientsAndNutrients", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DelikatessenDrehbuch.Models.IngredientMeasureQuantity", "IngredientMeasureQuantity")
                        .WithMany()
                        .HasForeignKey("IngredientMeasureQuantityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DelikatessenDrehbuch.Models.Measure", "Measure")
                        .WithMany()
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariant", "RecipeAiVariant")
                        .WithMany("IngredientRows")
                        .HasForeignKey("RecipeAiVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("IngredientMeasureQuantity");

                    b.Navigation("Measure");

                    b.Navigation("RecipeAiVariant");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariantSelectedIngredient", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.IngredientsAndNutrients", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariant", "RecipeAiVariant")
                        .WithMany("SelectedIngredients")
                        .HasForeignKey("RecipeAiVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("RecipeAiVariant");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeBaseKeyword", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.Keyword", "Keyword")
                        .WithMany("RecipeLinks")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "RecipeBaseData")
                        .WithMany("RecipeKeywords")
                        .HasForeignKey("RecipeBaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("RecipeBaseData");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldClipWatchSession", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserPosting", "Posting")
                        .WithMany()
                        .HasForeignKey("WorldUserPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserAbo", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldAppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldAppUser", "WorldUser")
                        .WithMany()
                        .HasForeignKey("WorldUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("WorldUser");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserBookmark", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldAppUser", "WorldAppUser")
                        .WithMany()
                        .HasForeignKey("WorldAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("WorldAppUser");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserLike", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldAppUser", "WorldAppUser")
                        .WithMany()
                        .HasForeignKey("WorldAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("WorldAppUser");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.WorldUserPosting", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Ingredient", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.IngredientHandlerModel", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Measure", "Measure")
                        .WithMany()
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Quantity", "Quantity")
                        .WithMany()
                        .HasForeignKey("QuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Measure");

                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.IngredientMeasureQuantity", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.IngredientsAndNutrients", "IngredientsAndNutrients")
                        .WithMany()
                        .HasForeignKey("IngredientsAndNutrientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Measure", "Measure")
                        .WithMany()
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Quantity", "Quantity")
                        .WithMany()
                        .HasForeignKey("QuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientsAndNutrients");

                    b.Navigation("Measure");

                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.IngredientsAndNutrients", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.FoodCategory", "FoodCategory")
                        .WithMany("Ingredients")
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Ingredients_FoodCategories");

                    b.HasOne("DelikatessenDrehbuch.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.Navigation("FoodCategory");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Like", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.Recipes", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.MealPlan", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.MyMealModel", "MyMealModel")
                        .WithMany()
                        .HasForeignKey("MyMealModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyMealModel");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.MealPlanHandler", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.MealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Recipes", "Recipes")
                        .WithMany()
                        .HasForeignKey("RecipesId");

                    b.Navigation("MealPlan");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.NutrienHandler", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Measure", "Metrics")
                        .WithMany()
                        .HasForeignKey("MetricsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Nutrients", "Nutrients")
                        .WithMany()
                        .HasForeignKey("NutrientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Quantity", "Quantity")
                        .WithMany()
                        .HasForeignKey("QuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Metrics");

                    b.Navigation("Nutrients");

                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.QueryHandler", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.Queries", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.Recipes", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.Recession", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.Recipes", "Recipes")
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeBaseDataImage", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeJoinIngredientMeasureQuantity", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.IngredientMeasureQuantity", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeJoinPreparationSteps", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.RecipePreparationSteps", "RecipePreparationStep")
                        .WithMany()
                        .HasForeignKey("RecipePreperationStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipePreparationStep");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeJoinSmartStep", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.RecipeBaseData", "Recipe")
                        .WithMany("SmartSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelikatessenDrehbuch.Models.SmartRecipeStep", "SmartRecipeStep")
                        .WithMany("RecipeLinks")
                        .HasForeignKey("SmartRecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("SmartRecipeStep");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipesHandler", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.IngredientHandlerModel", "IngredientHandler")
                        .WithMany()
                        .HasForeignKey("IngredientHandlerId");

                    b.HasOne("DelikatessenDrehbuch.Models.Recipes", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientHandler");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.UserPreferencesRecipe", b =>
                {
                    b.HasOne("DelikatessenDrehbuch.Models.Recipes", "Recipes")
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.Keyword", b =>
                {
                    b.Navigation("RecipeLinks");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Areas.WorldMiniApp.Models.RecipeAiVariant", b =>
                {
                    b.Navigation("IngredientRows");

                    b.Navigation("SelectedIngredients");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.FoodCategory", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.RecipeBaseData", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Ingredients");

                    b.Navigation("RecipeKeywords");

                    b.Navigation("SmartSteps");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DelikatessenDrehbuch.Models.SmartRecipeStep", b =>
                {
                    b.Navigation("RecipeLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
